# Use F keys
bind = , XF86AudioMute, exec, pamixer -t #F1
bind = , XF86AudioLowerVolume, exec, pamixer -d 1 #F2
bind = , XF86AudioRaiseVolume, exec, pamixer -i 1 #F3
bind = , XF86AudioMicMute, exec, sh -c 'wpctl set-mute @DEFAULT_SOURCE@ toggle' #F4
bind = , XF86MonBrightnessDown, exec, brightnessctl set 1%- #F5
bind = , XF86MonBrightnessUp, exec, brightnessctl set +1% # F6

# Close all AI
bind = $mainMod SHIFT, C, exec, bash -lc 'hyprctl clients -j | jq -r ".[] | select((.class // \"\" | test(\"^brave-(chat[.]openai[.]com|gemini[.]google[.]com)\"; \"i\")) or (.initialClass // \"\" | test(\"^brave-(chat[.]openai[.]com|gemini[.]google[.]com)\"; \"i\"))) | .address" | xargs -r -I{} hyprctl dispatch closewindow address:{}'
