# Main monitor
monitor = eDP-1, 1920x1080@60, 0x0, 1.2

# Mirror main on HDMI
monitor = HDMI-A-1, preferred, auto, 1, mirror, eDP-1

# Touchpad settings
input {
    touchpad {
        natural_scroll = yes
        scroll_factor = 0.3
        disable_while_typing = true
    }
}

device {
    name = synaptics-tm3625-010
    sensitivity = 0.6
}

device {
    name = tpps/2-elan-trackpoint
    sensitivity = 0.3
}
