#!/usr/bin/env bash
# Cleanup script if the user decides to remove the theme changer,
# while keeping the last generated and applied theme intact.

CONFIG="$HOME/.config"

echo "Starting Theme Changer cleanup..."

# Stop associated daemons
pkill awww-daemon || true

# Remove the downloaded wallpaper library (the current wallpaper is preserved in current_wallpaper)
rm -rf "$HOME/Pictures/wallpapers"

# Remove temporary files and caches generated by the new scripts
rm -rf "$HOME/.cache/wallust"
rm -rf "$HOME/.cache/wallpaper_rofi"
rm -rf "$HOME/.cache/gif_preview"
rm -rf "$HOME/.cache/video_preview"

# Remove the original templates for the various modules
rm -f "$CONFIG/waybar/template.css"
rm -f "$CONFIG/wlogout/template.css"
rm -f "$CONFIG/swaync/template.css"
rm -f "$CONFIG/oh-my-posh/themes/template.omp.json"
rm -f "$CONFIG/rofi/theme_changer.rasi"

# Remove the keyboard binding from Hyprland
TARGET_FILE="$CONFIG/hypr/hyprland.conf"
if [ -f "$TARGET_FILE" ]; then
    sed -i "\|bind = $mainMod SHIFT, T, exec, sh $HOME/.config/scripts/theme_changer/theme_chooser.sh # Change theme based on wallpaper|d" "$TARGET_FILE"
fi

# Remove pacman dependencies
for pkg in "${THEME_CHANGER_DEPENDENCIES_PACMAN[@]}"; do
    if pacman -Qi "$pkg" &>/dev/null; then
        sudo pacman -Rs --noconfirm "$pkg"
    fi
done

# Remove yay dependencies
for pkg in "${THEME_CHANGER_DEPENDENCIES_YAY[@]}"; do
    if pacman -Qi "$pkg" &>/dev/null; then
        sudo -u "$USER_NAME" -H yay -R --noconfirm "$pkg"
    fi
done

# Remove the Theme Changer scripts directory
rm -rf "$CONFIG/scripts/$THEME_CHANGER_SCRIPTS"

# Remove the sudoers rules added during installation
if [ -f "$SUDOERS_FILE" ]; then
    sudo rm -f "$SUDOERS_FILE"
fi

# Clean up all pre-generated themes
if [ -d "$CONFIG/themes" ]; then
    find "$CONFIG/themes" -mindepth 1 -maxdepth 1 -type d ! -name "current_wallpaper" -exec rm -rf {} +
fi

echo "Cleanup completed! The last applied theme will remain active on the system."
